version: '3'
services:

  #Laravel App
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=i53weLzCSdunQzNc2SXR2AE9XJVDuNaq
      - DB_HOST=db
      - DB_DATABASE=riot-api
      - DB_USERNAME=riot-api
      - DB_PASSWORD=root
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    links:
      - app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - .docker/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: riot-api
      MYSQL_USER: riot-api
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  mysqldata:
    driver: local
